<a href="https://colab.research.google.com/github/kavya-shetty765/Appilications-of-Python-Programming-in-DA-and-ML/blob/master/DAY3_Pandas_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a Pandas program to convert a Panda module Series to Python list and its type.

In [2]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))


Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


In [3]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)


Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


#Write a Pandas program to compare the elements of the two Pandas Series.
#Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]



In [4]:

import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)


Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


#Write a Pandas program to convert a dictionary to a Pandas series.
#Sample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}


In [5]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)


Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


Write a Pandas program to convert a NumPy array to a Pandas series.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50]


In [6]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)


NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


Write a Pandas program to change the data type of the given  Series into numeric
#['100', '200', 'python', '300.12', '400']



In [7]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)


Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


Write a Pandas program to convert a given Series to an array.

In [8]:
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


In [ ]:
Write a Pandas program to add some data to an existing Series.

In [10]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


Write a Pandas program to create a subset of a given series based on value and condition.

In [11]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)


Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


Write a Pandas program to change the order of index of a given series

In [12]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)


Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series.



In [13]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())


Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}


In [14]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)


    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


Write a NumPy program to generate five random numbers from the normal distribution.

In [18]:
import numpy as np
x = np.random.normal(size=5)
print(x)


[ 1.30869965 -0.34707666  0.2339724   0.79947561 -0.23995821]


Write a NumPy program to generate six random integers between 10 and 30

In [19]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)


[15 20 27 29 23 18]


Write a NumPy program to create a 3x3x3 array with random values

In [20]:
import numpy as np
x = np.random.random((3,3,3))
print(x)


[[[0.020401   0.18799227 0.9449713 ]
  [0.27659581 0.402925   0.43575845]
  [0.7066303  0.83762323 0.75878961]]

 [[0.57351322 0.73325778 0.26457483]
  [0.10703642 0.03274398 0.32350437]
  [0.43773375 0.72262998 0.45921022]]

 [[0.62188589 0.06315429 0.62524771]
  [0.33969442 0.40571138 0.62318767]
  [0.87777594 0.78445343 0.42945611]]]


Write a NumPy program to create a 5x5 array with random values and find the minimum #and maximum values

In [21]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.60058389 0.01539632 0.8346184  0.34936326 0.35993894]
 [0.03528343 0.34397529 0.00540438 0.23180623 0.76446746]
 [0.37535254 0.09708315 0.51319677 0.10822226 0.60727868]
 [0.11666229 0.64868049 0.3914886  0.27724838 0.2926077 ]
 [0.92477516 0.08790718 0.80337768 0.9273538  0.37486219]]
Minimum and Maximum Values:
0.005404381911468081 0.9273537976161274


Write a NumPy program to create a random 10x4 array and extract the first five rows of the # array and store them into a variable.

In [22]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)


Original array: 
[[0.12230458 0.16463058 0.85747425 0.57964612]
 [0.4439925  0.33326756 0.47673774 0.35875923]
 [0.04497536 0.39125223 0.33164648 0.41430182]
 [0.81408614 0.42066408 0.37209641 0.49905864]
 [0.17257081 0.57500746 0.68489726 0.20316448]
 [0.02747971 0.50420605 0.66232381 0.83432251]
 [0.86700294 0.39030069 0.56372647 0.42011834]
 [0.63571795 0.23899651 0.21351706 0.91648923]
 [0.84379799 0.13665724 0.77310391 0.09543816]
 [0.68375875 0.88858923 0.99319291 0.0308738 ]]
First 5 rows of the above array:
[[0.12230458 0.16463058 0.85747425 0.57964612]
 [0.4439925  0.33326756 0.47673774 0.35875923]
 [0.04497536 0.39125223 0.33164648 0.41430182]
 [0.81408614 0.42066408 0.37209641 0.49905864]
 [0.17257081 0.57500746 0.68489726 0.20316448]]
First 3 columns of the above array:
[[0.12230458 0.16463058 0.85747425 0.57964612]
 [0.4439925  0.33326756 0.47673774 0.35875923]
 [0.04497536 0.39125223 0.33164648 0.41430182]
 [0.81408614 0.42066408 0.37209641 0.49905864]
 [0.17257081 0.5750

Write a NumPy program to shuffle numbers and find permutation  between 0 and 10 #(inclusive).

In [23]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))


[9 3 0 1 8 7 5 6 4 2]
Same result using permutation():
[6 4 3 8 9 0 2 7 1 5]


Write a NumPy program to create a random integer nos of size 10 and sort it.

In [26]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)


[2 8 6 0 9 7 1 5 4 3]
[0 1 2 3 4 5 6 7 8 9]
